services:
  gamerank-backend:
    build: ./gamerank-backend
    container_name: gamerank-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/gamerank
    restart: always

  mongo:
    image: mongo
    container_name: gamerank-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
